/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Debug`; params?: Router.UnknownInputParams; } | { pathname: `/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/OnboardingIllustration`; params?: Router.UnknownInputParams; } | { pathname: `/Questionnaire`; params?: Router.UnknownInputParams; } | { pathname: `/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/MentalHealthIllustration` | `/MentalHealthIllustration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Signup` | `/Signup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Debug`; params?: Router.UnknownOutputParams; } | { pathname: `/Onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/OnboardingIllustration`; params?: Router.UnknownOutputParams; } | { pathname: `/Questionnaire`; params?: Router.UnknownOutputParams; } | { pathname: `/Welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/MentalHealthIllustration` | `/MentalHealthIllustration`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/Signup` | `/Signup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/Debug${`?${string}` | `#${string}` | ''}` | `/Onboarding${`?${string}` | `#${string}` | ''}` | `/OnboardingIllustration${`?${string}` | `#${string}` | ''}` | `/Questionnaire${`?${string}` | `#${string}` | ''}` | `/Welcome${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Login${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/MentalHealthIllustration${`?${string}` | `#${string}` | ''}` | `/MentalHealthIllustration${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/Signup${`?${string}` | `#${string}` | ''}` | `/Signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Debug`; params?: Router.UnknownInputParams; } | { pathname: `/Onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/OnboardingIllustration`; params?: Router.UnknownInputParams; } | { pathname: `/Questionnaire`; params?: Router.UnknownInputParams; } | { pathname: `/Welcome`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/MentalHealthIllustration` | `/MentalHealthIllustration`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/Signup` | `/Signup`; params?: Router.UnknownInputParams; };
    }
  }
}
